sonar.organization=elieahd
sonar.projectKey=elieahd_metrics
sonar.projectName=Metrics
sonar.language=java
sonar.sources=src/main/java/
sonar.java.binaries=target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
