name: Reusable Workflow - ✅ Checks

on: workflow_call

jobs:
  checks:
    name: ✅ Tests
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout code
        uses: actions/checkout@v6

      - name: ⚙️ Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: 🧪 Run tests
        run: mvn verify
